#!/usr/bin/env python3
"""Convert source PNGs into src/sprites.h as RGB565 C arrays.

Usage: python3 tools/gen_sprites.py <path-to-art-source-dir>

Looks up art/sprites/<name>.png first (in-repo, authoritative), falls back
to <art-source-dir>/<name>.png, and if neither exists, synthesizes a
checkerboard placeholder, caches it at art/sprites/<name>.png, and records
the miss. Any misses are written to ART_NEEDED.md at the repo root at the
end of the run (deleted if nothing is missing).
"""

import sys
import os
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("This script requires Pillow: pip install Pillow", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
IN_REPO_ART = REPO_ROOT / "art" / "sprites"
OUT_HEADER = REPO_ROOT / "src" / "sprites.h"
ART_NEEDED = REPO_ROOT / "ART_NEEDED.md"

TRANSPARENT_KEY = 0xF81F  # magenta

# name -> (relative source path, target width, target height)
SPRITE_MANIFEST = [
    # ("boss/idle_0", "boss/idle_0.png", 96, 96),
]

missing = []


def pack_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def synthesize_placeholder(path: Path, w: int, h: int, tag: str):
    img = Image.new("RGBA", (w, h), (255, 0, 255, 255))
    draw = ImageDraw.Draw(img)
    cell = max(4, w // 8)
    for y in range(0, h, cell):
        for x in range(0, w, cell):
            if ((x // cell) + (y // cell)) % 2 == 0:
                draw.rectangle([x, y, x + cell - 1, y + cell - 1], fill=(64, 64, 64, 255))
    draw.text((2, 2), tag[:12], fill=(255, 255, 0, 255))
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path)
    return img


def open_or_placeholder(rel_path: str, art_source_dir: Path, w: int, h: int, tag: str):
    in_repo = IN_REPO_ART / rel_path
    external = art_source_dir / rel_path if art_source_dir else None

    if in_repo.exists():
        return Image.open(in_repo).convert("RGBA")
    if external and external.exists():
        return Image.open(external).convert("RGBA")

    missing.append((rel_path, w, h, tag))
    return synthesize_placeholder(in_repo, w, h, tag).convert("RGBA")


def convert_sprite(name: str, rel_path: str, art_source_dir: Path, w: int, h: int):
    img = open_or_placeholder(rel_path, art_source_dir, w, h, name)
    img = img.resize((w, h), Image.NEAREST)

    pixels = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = img.getpixel((x, y))
            if a < 128:
                pixels.append(TRANSPARENT_KEY)
            else:
                pixels.append(pack_rgb565(r, g, b))
    return pixels


def main():
    art_source_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else None

    lines = [
        "/* AUTO-GENERATED by tools/gen_sprites.py -- do not edit by hand. */",
        "#ifndef SPRITES_H",
        "#define SPRITES_H",
        "",
        "#include <stdint.h>",
        "",
    ]

    for name, rel_path, w, h in SPRITE_MANIFEST:
        pixels = convert_sprite(name, rel_path, art_source_dir, w, h)
        c_name = name.replace("/", "_")
        lines.append(f"#define {c_name.upper()}_W {w}")
        lines.append(f"#define {c_name.upper()}_H {h}")
        lines.append(f"static const uint16_t {c_name}[] = {{")
        row = ", ".join(str(p) for p in pixels)
        lines.append(f"    {row}")
        lines.append("};")
        lines.append("")

    lines.append("#endif")

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_HEADER.write_text("\n".join(lines))
    print(f"Wrote {OUT_HEADER} ({len(SPRITE_MANIFEST)} sprites)")

    if missing:
        manifest_lines = ["# ART_NEEDED", "", "Missing assets (placeholders synthesized):", ""]
        for rel_path, w, h, tag in missing:
            manifest_lines.append(f"- `art/sprites/{rel_path}` -- {w}x{h}px, entity/purpose: {tag}")
        manifest_lines.append("")
        manifest_lines.append(
            "Generate replacement art at the exact path and pixel size above, "
            "RGBA PNG, transparent background."
        )
        ART_NEEDED.write_text("\n".join(manifest_lines))
        print(f"{len(missing)} asset(s) missing -- see {ART_NEEDED}")
    elif ART_NEEDED.exists():
        ART_NEEDED.unlink()


if __name__ == "__main__":
    main()
